### ISSUE TITLE
Using isMotionEnabled on BottomNavigationController/UITabBarController causes delegate methods to not be called

### ISSUE THREAD

**Issue by andrewc94** [CosmicMind/Motion#27]
It seems as though setting the delegate on a BottomNavigationController causes Motion to be disabled while enabling Motion causes delegate methods to not be called.

Material 2.13.5
Motion 1.3.4

[BottomNavigationController.zip](https://github.com/CosmicMind/Motion/files/1721754/BottomNavigationController.zip)

**Comment by daniel-jonathan** [comment]
I will take a look at your sample. Thank you for sharing this issue.

**Comment by daniel-jonathan** [comment]
@OrkhanAlikhanov Let's confirm if this is still an issue. Thank you and apologies for taking a very long time to respond.

**Comment by OrkhanAlikhanov** [comment]
@danieldahan I confirm that this issue is still there. I investigated it a bit. Here is my summary.

### The issue
Setting `isMotionEnabled = true` changes the `delegate` but does not forward the delegation methods to `previousTabBarDelegate`.
```swift
class AppBottomNavigationController: BottomNavigationController {
  override func prepare() {
        super.prepare()
        delegate = self
        print(delegate === self) // true
        isMotionEnabled = true // changes `delegate`
        print(delegate === self) // false

        isMotionEnabled = false // sets `previousTabBarDelegate` back
        print(delegate === self) // true
    }
}

extension AppBottomNavigationController: UITabBarControllerDelegate {
    func tabBarController(_ tabBarController: UITabBarController, didSelect viewController: UIViewController) {
        print("hi") // never called if `isMotionEnabled == true`
    }
}
```

### Possible solution
I think forwarding delegation methods to the `tabBarController.previousTabBarDelegate` will solve the problem but I am unsure about its side effects. Here is the file where it should be done.
https://github.com/CosmicMind/Motion/blob/b3595d023fdd3b64dede8c30bcaa08ee366cf249/Sources/Transition/MotionTransition%2BUITabBarControllerDelegate.swift#L31-L32

**Comment by daniel-jonathan** [comment]
@OrkhanAlikhanov I believe this issue may be closed. Please take a look at [Motion 1.4.2](https://github.com/CosmicMind/Motion/releases/tag/1.4.2) to test if this is still an issue. Thank you!
