### ISSUE TITLE
.hidesBottomBarWhenPushed = true smooth transition when pushing

### ISSUE THREAD

**Issue by roteirod** [CosmicMind/Motion#73]
I use UITabBarController and UINavigationController in my app. I am pushing another view using custom transition and in need to hide tab bar after push. But I can't make it smooth, it just disappears immediately when the second view controller is pushed

**Comment by daniel-jonathan** [comment]
Hi @roteirod thank you for sharing your issue. Can you share your setup code or sample project that we may play with and help you out?

**Comment by roteirod** [comment]
Here is what I do in my first viewController which is inside a navigationController inside a tabBarcontroller 
```
override func viewDidLoad() {
        super.viewDidLoad()
        navigationController?.isMotionEnabled = true
        navigationController?.motionNavigationTransitionType = .none
}
```

I also setup all the identifiers for transition here
```
        self.motionIdentifier = "avatar"
        lblName.motionIdentifier = "name"
        scrollView.motionIdentifier = "verified"
```

Then I push the second viewController
```
if let profile = ProfileViewController.storyboardInstance() {
            profile.userProfile = userProfile
            profile.delegate = self
            
            profile.hidesBottomBarWhenPushed = true
            navigationController?.pushViewController(profile, animated: true)
        }
```

Where I do this
```
        self.isMotionEnabled = true
        avatarCollectionView.motionIdentifier = "avatar"
        nameDistanceLabel.motionIdentifier = "name"
        verifiedBadge.motionIdentifier = "verified"
        profileTableView.transition(.fade(1))
```

The transitions which I set identifiers for work amazingly. But the tab bar is visible for a fraction of time after the transition and then disappears abruptly

**Comment by adamdahan** [comment]
@roteirod It is really difficult for us to experience this issue first hand to help you with a fix. We would literally have to replicate the situation of your controllers by hand in order to test it. Without a sample project it's hard to diagnose. 

I would suggest: Take your storyboard & Accompanying view controllers and put them into a new simple project that demonstrates the issue first hand. 

That will let us experience it and see how to go from there.

**Comment by roteirod** [comment]
Ok, I set up a primitive project which has the same structure as my main one: 

![ezgif-5-e2e652d53d34](https://user-images.githubusercontent.com/36671280/64544045-fdb58980-d32e-11e9-8ffb-1cc270c1ad24.gif)

[tabbarissue.zip](https://github.com/CosmicMind/Motion/files/3591283/tabbarissue.zip)

**Comment by roteirod** [comment]
The gray thing is a Tab Bar :D

**Comment by adamdahan** [comment]
@roteirod wonderful. Will get back to you as soon as possible :)

**Comment by roteirod** [comment]
Thank you so much!

It does not look that bad on this gif. But it is worse if you run the project. Can I get a smooth fadeOut-fadeIn animation for Tab bar somehow?

**Comment by adamdahan** [comment]
@roteirod Ok fixed. 

In Motion... you need to have a starting point for the animation. Let's call that animate from: then you need to have an finish point for the animation let's call that animate to:

In the case of your button you have two corresponding motionIdentifiers assigned "view". So the animation works as expected. 

But in the case of the tabBarController.tabBar = you have no such tab bar on the second controller because you call hidesBottomBarWhenPushed = true on the first controller. 

I've included some sample code for an approach to fix this issue. Simply by fading the tab bar in and out using MotionAnimation. Hope this helps!

```
//
//  ViewController.swift
//  tabbarissue
//
//  Created by Volodymyr on 9/9/19.
//  Copyright © 2019 Volodymyr Davydenko. All rights reserved.
//

import UIKit
import Motion

class FirstViewController: UIViewController {
  
  static func instantiateViewController() -> FirstViewController {
    let name = String(describing: FirstViewController.self)
    let storyboard = UIStoryboard(name: name, bundle: nil)
    let viewController = storyboard.instantiateViewController(withIdentifier: name) as! FirstViewController
    return viewController
  }
  
  @IBOutlet weak var performTransitionButton: UIButton!
  
  override func viewWillAppear(_ animated: Bool) {
    super.viewWillAppear(animated)
    tabBarController?.tabBar.animate(.fadeIn)
  }
  
  override func viewDidLoad() {
    super.viewDidLoad()
    
    navigationController?.isMotionEnabled = true
    navigationController?.motionNavigationTransitionType = .none
    performTransitionButton.motionIdentifier = "view"
  }
  
  @IBAction func performTransition(_ sender: Any) {
    let secondVC = SecondViewController.instantiateViewController()
    tabBarController?.tabBar.animate(.fadeOut)
    navigationController?.pushViewController(secondVC, animated: true)
  }
}
```

![fade (1)](https://user-images.githubusercontent.com/1205894/64714925-7f232e00-d48d-11e9-8ae6-391bd7761da7.gif)

**Comment by adamdahan** [comment]
@roteirod Feel free to play with the animation fade duration to suit your needs :)

**Comment by adamdahan** [comment]
@roteirod i've edited my answer to give you a smooth animation that has the same duration as your red box. See above example again.

**Comment by roteirod** [comment]
That's awesome, thank you!

**Comment by adamdahan** [comment]
Np! @roteirod
